apiVersion: apps/v1
kind: Deployment
metadata:
  name: koncepts-demo
spec:
  template:
    spec:
      containers:
        - name: koncepts
          env:
            - name: ENVIRONMENT
              value: PROD