apiVersion: apps/v1
kind: Deployment
metadata:
  name: koncepts-demo
spec:
  template:
    spec:
      containers:
        - name: koncepts
          env:
            - name: ENVIRONMENT
              value: PROD
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-config
data:
  config.txt: This is the Prod config