apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: koncepts-demo
spec:
  path: /
  to:
    kind: Service
    name: koncepts-demo
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect